# Generated by Django 5.2.4 on 2025-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance')], max_length=50)),
                ('platform', models.CharField(choices=[('Netflix', 'Netflix'), ('Prime Video', 'Prime Video'), ('Disney+ Hotstar', 'Disney+ Hotstar'), ('HBO Max', 'HBO Max')], max_length=50)),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Completed', 'Completed'), ('Wishlist', 'Wishlist')], max_length=50)),
            ],
        ),
    ]
