# Generated by Django 5.2.4 on 2025-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
